# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'ZHChattingDemo' do

pod 'XMPPFramework', '~> 3.6.6'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZHChattingDemo

  target 'ZHChattingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZHChattingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
